// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/common/Setting/About.vue')['default']
    Button: typeof import('./src/components/common/HoverButton/Button.vue')['default']
    General: typeof import('./src/components/common/Setting/General.vue')['default']
    GithubSite: typeof import('./src/components/custom/GithubSite.vue')['default']
    HoverButton: typeof import('./src/components/common/HoverButton/index.vue')['default']
    PromptStore: typeof import('./src/components/common/PromptStore/index.vue')['default']
    RightContent: typeof import('./src/components/RightContent/RightContent.vue')['default']
    Setting: typeof import('./src/components/common/Setting/index.vue')['default']
    SettingDrawer: typeof import('./src/components/SettingDrawer/SettingDrawer.vue')['default']
    SvgIcon: typeof import('./src/components/common/SvgIcon/index.vue')['default']
    UserAvatar: typeof import('./src/components/common/UserAvatar/index.vue')['default']
    VanIcon: typeof import('vant/es')['Icon']
  }
}

export { }
